doctor/urls.py
from django.urls import path,include
from doctor import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

    path('add_patient',views.add_patient,name="add_patient"),
    path('show_patient',views.show_patient,name="show_patient"),
    path('profile_researcher', views.researcher_profile, name="profile_researcher"),
    path('profile_doctor', views.doctor_profile, name="profile_doctor"),
    path('otp_verify', views.otp_verify_send, name="otp_verify"),
    path('add_disease_patient/<str:id>', views.add_disease_patient, name='add_disease_patient'),
    path('user_profile', views.profile, name="profile_user"),
    path('show_disease', views.show_disease, name="show_disease"),
    path('verify_otp', views.verify_otp, name="verify_otp"),
    path('show_patient_details/<str:id>', views.show_patient_details, name="show_patient_details"),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('signup_researcher',views.ResearcherSignup,name='signup_researcher'),
    path('signup_doctor',views.DoctorSignup,name='signup_doctor'),
    path('activate/<uidb64>/<token>',views.ActivateAccountView.as_view(), name='activate'),
    path('login',views.login_view,name='login'),
    path('logout', views.logout_view,name='logout'),
    path('request-reset-email',views.RequestResetEmail.as_view(),name='request-reset-email'),
    path('set-new-password/<uidb64>/<token>',views.SetNewPasswordView.as_view(), name='set-new-password'),
    path('user/',include('doctor.urls') ),
    
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/models.py
from django.db import models
from account.models import *
import os 
import uuid
# Create your models here.

TypeofBlooadGroup = (
    ("A+","A+"),
    ("A-","A-"),
    ("B+","B+"),
    ("B-","B-"),
    ("AB+","AB+"),
    ("AB-","AB-"),
    ("O+","O+"),
    ("O-","O-"),
)

class ResearcherProfile(models.Model):
    GENDER = (('M','MALE'),('F','FEMALE'))
    researcher = models.OneToOneField(User,on_delete=models.CASCADE)
    gender = models.CharField(default='M',choices=GENDER, max_length=1)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=10,null=True)
    dob = models.DateField()
    otp = models.CharField(max_length=5,null=True,blank=True)
    verified_phone = models.BooleanField(default=False,null=True)
    organization = models.CharField(max_length=255,null=True)
    country = models.CharField(max_length=255,null=True)
    country_code = models.CharField(max_length=2, default="91")

    def __str__(self):
        return self.first_name

class DoctorProfile(models.Model):
    GENDER = (('M','MALE'),('F','FEMALE'))
    doctor = models.OneToOneField(User,on_delete=models.CASCADE)
    gender = models.CharField(default='M',choices=GENDER, max_length=1)
    otp = models.CharField(max_length=5,null=True,blank=True)
    verified_phone = models.BooleanField(default=False,null=True)
    first_name = models.CharField(max_length=255)
    license_key = models.CharField(max_length=255)
    verified_admin = models.BooleanField(default=False,null=True)
    last_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=10,null=True)
    dob = models.DateField()
    specialization = models.CharField(max_length=255,null=True)
    country_code = models.CharField(max_length=2, default="91")

    def __str__(self):
        return self.first_name

class PatientProfile(models.Model):
    GENDER = (('M','MALE'),('F','FEMALE'))
    added_by = models.ForeignKey(User,on_delete=models.CASCADE)
    gender = models.CharField(default='M',choices=GENDER, max_length=1)
    first_name = models.CharField(max_length=255)
    blood_group = models.CharField(max_length=3,choices=TypeofBlooadGroup,default='A+')
    hospital = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone = models.IntegerField()
    dob = models.DateField()

    def __str__(self):
        return self.first_name


def get_upload_path(instance, filename):
    ext = filename.split('.')[-1]
    # get filename
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        filename = "%s.%s" % (uuid.uuid4(), ext)
        # filename= instance.name + instance.modality + uuid.uuid4()
    return os.path.join(
      "%s" % instance.name, "%s" % instance.modality, filename)

Possibility = (
("YES", "YES"),
("NO", "NO"),
)

TypeofModality = (
    ("X-ray","X-ray"),
    ("CT-scan","CT-scan"),
    ("MRI","MRI"),
    ("UltraSound","Ultrasound"),
    ("Angiography","Angiography"),
    ("Electrocardiogram","ECG"),
    ("PET","PET"),
    ("OCT","OCT")
)



MEDIA_CHOICES = [
    ('Audio', (
            ('vinyl', 'Vinyl'),
            ('cd', 'CD'),
        )
    ),
    ('Video', (
            ('vhs', 'VHS Tape'),
            ('dvd', 'DVD'),
        )
    ),
    ('unknown', 'Unknown'),
]

class DiseaseDetails(models.Model):
    patient = models.ForeignKey(PatientProfile,on_delete=models.CASCADE)
    name = models.CharField(max_length=30,null=True)
    organ = models.CharField(max_length=100,null=True)
    modality=models.CharField(max_length=30,choices=TypeofModality,default='X-ray')
    diagonised = models.CharField(max_length = 20, choices = Possibility, default = 'YES')
    img=models.ImageField(upload_to=get_upload_path,null=True)
    date = models.DateTimeField(null=True)

    def __str__(self):
        return self.name

researcher/models.py
from django.db import models

# Create your models here.

researcher/views.py
from django.shortcuts import render

# Create your views here.

templates/researcher/profile-form.html
{% extends 'basic.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
<section class="formtwo">
  <div class="container">


    <div class="row">
      <div class="col-6 border-right">
        <h1 class="subheading">Create your Profile</h1>
      </div>
      <div class="col-6 form">
        <form method="POST">
          {% csrf_token %}
          <h5 class="row">First Name</h5>
          <div class="row">
            <br>
            {{ form.first_name }}
          </div>
          <h5 class="row">Last Name</h5>
          <div class="row">

            {{ form.last_name}}
          </div>
          <h5 class="row">Gender</h5>
          <div class="row">

            {{ form.gender }}
          </div>
          
          <h5 class="row">Phone No.</h5>
          <div class="row">

            {{ form.phone}}
          </div>
          <h5 class="row">Date of Birth</h5>
          <div class="row">

            {{ form.dob}}
          </div>

          <h5 class="row">Organization</h5>
          <div class="row">

            {{ form.organization}}
          </div>
          <h5 class="row">Country</h5>
          <div class="row">

            {{ form.country}}
          </div>

          <div class="row">
            <button type="submit" class="titlebutton formbtn btn btn-md">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock body %}

templates/researcher/profile.html
{% extends 'basic.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
  <div class="card mb-3 mt-3">
    <div class="card-body" style="background-color:#fff">
      <h1 class="card-title">{{researcher.first_name}} {{researcher.last_name}}</h1>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>Gender:</td>
            <td>{{researcher.get_gender_display}}</td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>Email Id:</td>
            <td>{{researcher.researcher.email}}</td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>Phone No.:</td>
            <td>{{researcher.phone}}</td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>Organization: </td>
            <td>{{researcher.organization}}</td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>Country: </td>
            <td>{{researcher.country}}</td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>Date of Birth: </td>
            <td>{{researcher.dob}}</td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </tbody>
      </table>
    </div>

  </div>
  {% if researcher.verified_phone %}
  <h2> Your phone is already verified</h2>
  {% else %}
  <button class="btn-primary"><a class="nav-link" href="{%url 'otp_verify'%}">OTP Verify</a></button>
  {% endif%}
  
</div>

{% endblock body %}